behaviors:
    Penguin:
        trainer_type: ppo
        hyperparameters:
            batch_size: 640
            buffer_size: 4096
            learning_rate: 0.0001
            beta: 0.01
            epsilon: 0.2 
            lambd: 1
            num_epoch: 5
            learning_rate_schedule: linear
        network_settings:
            normalize: true
            hidden_units: 512
            num_layers: 5
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
        keep_checkpoints: 5
        max_steps: 1500000
        time_horizon: 256
        summary_freq: 5000
        threaded: true